"""empty message

Revision ID: 123a8ad98011
Revises: 2eb3f02a310e
Create Date: 2021-09-13 15:44:45.445769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123a8ad98011'
down_revision = '2eb3f02a310e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('orders_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('day')
    # ### end Alembic commands ###
