"""empty message

Revision ID: 2ae3af2fa751
Revises: 123a8ad98011
Create Date: 2021-09-13 17:23:22.893141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae3af2fa751'
down_revision = '123a8ad98011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'day', ['date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'day', type_='unique')
    # ### end Alembic commands ###
