"""empty message

Revision ID: 2eb3f02a310e
Revises: dca5e2da6020
Create Date: 2021-09-12 15:46:16.017320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eb3f02a310e'
down_revision = 'dca5e2da6020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manager')
    op.add_column('user', sa.Column('manager', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'manager')
    op.create_table('manager',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=20), nullable=False),
    sa.Column('rank', sa.INTEGER(), nullable=False),
    sa.Column('password', sa.VARCHAR(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
