"""empty message

Revision ID: b3abfc657137
Revises: 
Create Date: 2021-09-15 09:44:21.240064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3abfc657137'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('orders_amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('stop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('manager', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FCs', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('departure_point', sa.String(length=40), nullable=False),
    sa.Column('arrival_point', sa.String(length=40), nullable=False),
    sa.Column('order_type', sa.String(length=15), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stops_table',
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('stop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stop.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stops_table')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('stop')
    op.drop_table('day')
    # ### end Alembic commands ###
